[InstallSHIELD Silent]
Version=v3.00.000
File=Response File
[Application]
Name=Nokia Cellular Data Suite
Version=1.2
Company=Nokia
[DlgOrder]
Count=5
Dlg0=SdWelcome-0
Dlg1=SdLicense-0
Dlg2=SdSetupType-0
Dlg3=SdStartCopy-0
Dlg4=SdFinishReboot-0

[SdWelcome-0]
Result=1

[SdLicense-0]
Result=1

[SdSetupType-0]
Result=301
szDir=C:\Program Files\Data Suite

[SdStartCopy-0]
Result=1

[SdFinishReboot-0]
Result=1
BootOption=0

