[InstallSHIELD Silent]
Version=v3.00.00
File=Response File

[DlgOrder]
Dlg0=SdWelcome-0
Dlg1=SdRegisterUser-0
Dlg2=SdAskDestPath-0
Dlg3=SdSelectFolder-0
Dlg4=SdStartCopy-0
Dlg5=SdFinish-0
Count=6

[SdWelcome-0]
Result=1

[SdRegisterUser-0]
Result=1
szName=Name
szCompany=Borland

[SdAskDestPath-0]
Result=1
szDir=<ProgramFilesDir>\Borland\Database Desktop

[SdSelectFolder-0]
Result=1
szFolder=DBD

[SdStartCopy-0]
Result=1

[SdFinish-0]
Result=0
bOpt1=0
bOpt2=0
