10 DIM A$(16, 16)
100 LET A$(1, 1) = "0"
101 LET A$(1, 2) = "1"
102 LET A$(1, 3) = "2"
103 LET A$(1, 4) = "3"
104 LET A$(1, 5) = "4"
105 LET A$(1, 6) = "5"
106 LET A$(1, 7) = "6"
107 LET A$(1, 8) = "7"
108 LET A$(1, 9) = "8"
109 LET A$(1, 10) = "9"
110 LET A$(1, 11) = "A"
111 LET A$(1, 12) = "B"
112 LET A$(1, 13) = "C"
113 LET A$(1, 14) = "D"
114 LET A$(1, 15) = "E"
115 LET A$(1, 16) = "F"

200 LET A$(2, 1) = "1"
201 LET A$(2, 2) = "0"
202 LET A$(2, 3) = "3"
203 LET A$(2, 4) = "2"
204 LET A$(2, 5) = "5"
205 LET A$(2, 6) = "4"
206 LET A$(2, 7) = "7"
207 LET A$(2, 8) = "6"
208 LET A$(2, 9) = "9"
209 LET A$(2, 10) = "8"
210 LET A$(2, 11) = "B"
211 LET A$(2, 12) = "A"
212 LET A$(2, 13) = "D"
213 LET A$(2, 14) = "C"
214 LET A$(2, 15) = "F"
215 LET A$(2, 16) = "E"

300 LET A$(3, 1) = "2"
301 LET A$(3, 2) = "3"
302 LET A$(3, 3) = "0"
303 LET A$(3, 4) = "1"
304 LET A$(3, 5) = "6"
305 LET A$(3, 6) = "7"
306 LET A$(3, 7) = "4"
307 LET A$(3, 8) = "5"
308 LET A$(3, 9) = "A"
309 LET A$(3, 10) = "B"
310 LET A$(3, 11) = "8"
311 LET A$(3, 12) = "9"
312 LET A$(3, 13) = "E"
313 LET A$(3, 14) = "F"
314 LET A$(3, 15) = "C"
315 LET A$(3, 16) = "D"

400 LET A$(4, 1) = "3"
401 LET A$(4, 2) = "2"
402 LET A$(4, 3) = "1"
403 LET A$(4, 4) = "0"
404 LET A$(4, 5) = "7"
405 LET A$(4, 6) = "6"
406 LET A$(4, 7) = "5"
407 LET A$(4, 8) = "4"
408 LET A$(4, 9) = "B"
409 LET A$(4, 10) = "A"
410 LET A$(4, 11) = "9"
411 LET A$(4, 12) = "8"
412 LET A$(4, 13) = "F"
413 LET A$(4, 14) = "E"
414 LET A$(4, 15) = "D"
415 LET A$(4, 16) = "C"

500 LET A$(5, 1) = "4"
501 LET A$(5, 2) = "5"
502 LET A$(5, 3) = "6"
503 LET A$(5, 4) = "7"
504 LET A$(5, 5) = "0"
505 LET A$(5, 6) = "1"
506 LET A$(5, 7) = "2"
507 LET A$(5, 8) = "3"
508 LET A$(5, 9) = "C"
509 LET A$(5, 10) = "D"
510 LET A$(5, 11) = "E"
511 LET A$(5, 12) = "F"
512 LET A$(5, 13) = "8"
513 LET A$(5, 14) = "9"
514 LET A$(5, 15) = "A"
515 LET A$(5, 16) = "B"

600 LET A$(6, 1) = "5"
601 LET A$(6, 2) = "4"
602 LET A$(6, 3) = "7"
603 LET A$(6, 4) = "6"
604 LET A$(6, 5) = "1"
605 LET A$(6, 6) = "0"
606 LET A$(6, 7) = "3"
607 LET A$(6, 8) = "2"
608 LET A$(6, 9) = "D"
609 LET A$(6, 10) = "C"
610 LET A$(6, 11) = "F"
611 LET A$(6, 12) = "E"
612 LET A$(6, 13) = "9"
613 LET A$(6, 14) = "8"
614 LET A$(6, 15) = "B"
615 LET A$(6, 16) = "A"

700 LET A$(7, 1) = "6"
701 LET A$(7, 2) = "7"
702 LET A$(7, 3) = "4"
703 LET A$(7, 4) = "5"
704 LET A$(7, 5) = "2"
705 LET A$(7, 6) = "3"
706 LET A$(7, 7) = "0"
707 LET A$(7, 8) = "1"
708 LET A$(7, 9) = "E"
709 LET A$(7, 10) = "F"
710 LET A$(7, 11) = "C"
711 LET A$(7, 12) = "D"
712 LET A$(7, 13) = "A"
713 LET A$(7, 14) = "B"
714 LET A$(7, 15) = "8"
715 LET A$(7, 16) = "9"

800 LET A$(8, 1) = "7"
801 LET A$(8, 2) = "6"
802 LET A$(8, 3) = "5"
803 LET A$(8, 4) = "4"
804 LET A$(8, 5) = "3"
805 LET A$(8, 6) = "2"
806 LET A$(8, 7) = "1"
807 LET A$(8, 8) = "0"
808 LET A$(8, 9) = "F"
809 LET A$(8, 10) = "E"
810 LET A$(8, 11) = "D"
811 LET A$(8, 12) = "C"
812 LET A$(8, 13) = "B"
813 LET A$(8, 14) = "A"
814 LET A$(8, 15) = "9"
815 LET A$(8, 16) = "8"

900 LET A$(9, 1) = "8"
901 LET A$(9, 2) = "9"
902 LET A$(9, 3) = "A"
903 LET A$(9, 4) = "B"
904 LET A$(9, 5) = "C"
905 LET A$(9, 6) = "D"
906 LET A$(9, 7) = "E"
907 LET A$(9, 8) = "F"
908 LET A$(9, 9) = "0"
909 LET A$(9, 10) = "1"
910 LET A$(9, 11) = "2"
911 LET A$(9, 12) = "3"
912 LET A$(9, 13) = "4"
913 LET A$(9, 14) = "5"
914 LET A$(9, 15) = "6"
915 LET A$(9, 16) = "7"

1000 LET A$(10, 1) = "9"
1001 LET A$(10, 2) = "8"
1002 LET A$(10, 3) = "B"
1003 LET A$(10, 4) = "A"
1004 LET A$(10, 5) = "D"
1005 LET A$(10, 6) = "C"
1006 LET A$(10, 7) = "F"
1007 LET A$(10, 8) = "E"
1008 LET A$(10, 9) = "1"
1009 LET A$(10, 10) = "0"
1010 LET A$(10, 11) = "3"
1011 LET A$(10, 12) = "2"
1012 LET A$(10, 13) = "5"
1013 LET A$(10, 14) = "4"
1014 LET A$(10, 15) = "7"
1015 LET A$(10, 16) = "6"


1100 LET A$(11, 1) = "A"
1101 LET A$(11, 2) = "B"
1102 LET A$(11, 3) = "8"
1103 LET A$(11, 4) = "9"
1104 LET A$(11, 5) = "E"
1105 LET A$(11, 6) = "F"
1106 LET A$(11, 7) = "C"
1107 LET A$(11, 8) = "D"
1108 LET A$(11, 9) = "2"
1109 LET A$(11, 10) = "3"
1110 LET A$(11, 11) = "0"
1111 LET A$(11, 12) = "1"
1112 LET A$(11, 13) = "6"
1113 LET A$(11, 14) = "7"
1114 LET A$(11, 15) = "4"
1115 LET A$(11, 16) = "5"

1200 LET A$(12, 1) = "B"
1201 LET A$(12, 2) = "A"
1202 LET A$(12, 3) = "9"
1203 LET A$(12, 4) = "8"
1204 LET A$(12, 5) = "F"
1205 LET A$(12, 6) = "E"
1206 LET A$(12, 7) = "D"
1207 LET A$(12, 8) = "C"
1208 LET A$(12, 9) = "3"
1209 LET A$(12, 10) = "2"
1210 LET A$(12, 11) = "1"
1211 LET A$(12, 12) = "0"
1212 LET A$(12, 13) = "7"
1213 LET A$(12, 14) = "6"
1214 LET A$(12, 15) = "5"
1215 LET A$(12, 16) = "4"

1300 LET A$(13, 1) = "C"
1301 LET A$(13, 2) = "D"
1302 LET A$(13, 3) = "E"
1303 LET A$(13, 4) = "F"
1304 LET A$(13, 5) = "8"
1305 LET A$(13, 6) = "9"
1306 LET A$(13, 7) = "A"
1307 LET A$(13, 8) = "B"
1308 LET A$(13, 9) = "4"
1309 LET A$(13, 10) = "5"
1310 LET A$(13, 11) = "6"
1311 LET A$(13, 12) = "7"
1312 LET A$(13, 13) = "0"
1313 LET A$(13, 14) = "1"
1314 LET A$(13, 15) = "2"
1315 LET A$(13, 16) = "3"

1400 LET A$(14, 1) = "D"
1401 LET A$(14, 2) = "C"
1402 LET A$(14, 3) = "F"
1403 LET A$(14, 4) = "E"
1404 LET A$(14, 5) = "9"
1405 LET A$(14, 6) = "8"
1406 LET A$(14, 7) = "B"
1407 LET A$(14, 8) = "A"
1408 LET A$(14, 9) = "5"
1409 LET A$(14, 10) = "4"
1410 LET A$(14, 11) = "7"
1411 LET A$(14, 12) = "6"
1412 LET A$(14, 13) = "1"
1413 LET A$(14, 14) = "0"
1414 LET A$(14, 15) = "3"
1415 LET A$(14, 16) = "2"

1500 LET A$(15, 1) = "E"
1501 LET A$(15, 2) = "F"
1502 LET A$(15, 3) = "C"
1503 LET A$(15, 4) = "D"
1504 LET A$(15, 5) = "A"
1505 LET A$(15, 6) = "B"
1506 LET A$(15, 7) = "8"
1507 LET A$(15, 8) = "9"
1508 LET A$(15, 9) = "6"
1509 LET A$(15, 10) = "7"
1510 LET A$(15, 11) = "4"
1511 LET A$(15, 12) = "5"
1512 LET A$(15, 13) = "2"
1513 LET A$(15, 14) = "3"
1514 LET A$(15, 15) = "0"
1515 LET A$(15, 16) = "1"

1600 LET A$(16, 1) = "F"
1601 LET A$(16, 2) = "E"
1602 LET A$(16, 3) = "D"
1603 LET A$(16, 4) = "C"
1604 LET A$(16, 5) = "B"
1605 LET A$(16, 6) = "A"
1606 LET A$(16, 7) = "9"
1607 LET A$(16, 8) = "8"
1608 LET A$(16, 9) = "7"
1609 LET A$(16, 10) = "6"
1610 LET A$(16, 11) = "5"
1611 LET A$(16, 12) = "4"
1612 LET A$(16, 13) = "3"
1613 LET A$(16, 14) = "2"
1614 LET A$(16, 15) = "1"
1615 LET A$(16, 16) = "0"

1700 CLS
1721 PRINT : PRINT : PRINT : PRINT : PRINT
1722 PRINT "         ********************************************************     "
1723 PRINT "         * KALKULATOR TABELI XOR DO KODOWANYCH RADIOODBIORNIKàW *     "
1724 PRINT "         *                                                      *     "
1725 PRINT "         *       MARKI GRUNDIG   @ ArtHacker    (c) 1993        *     "
1726 PRINT "         ********************************************************     "
1727 FOR L1 = 0 TO 50000: NEXT L1

2000 CLS : PRINT : PRINT : PRINT
2005 INPUT "PIERWSZA WARTO—    ="; B$
2007 INPUT "DRUGA WARTO—       ="; c$
2010 INPUT "TRZECIA WARTO—     ="; D$
2015 INPUT "CZWARTA WERTO—     ="; E$
2018 CLS : PRINT : PRINT "DANE ZGODNE ? "
2020 PRINT : PRINT "      "; B$; c$; " "; D$; E$:
2026 PRINT : PRINT "NACI—NIJ:  >N< -DLA NIE    I > ENTER< ";
2027 INPUT S$
2028 IF S$ = "N" THEN GOTO 2000
2029 IF S$ = "n" THEN GOTO 2000

2120 IF B$ >= "0" OR B$ <= "9" THEN L1 = VAL(B$)
2121 IF B$ = "A" THEN LET L1 = 10
2122 IF B$ = "B" THEN LET L1 = 11
2123 IF B$ = "C" THEN LET L1 = 12
2124 IF B$ = "D" THEN LET L1 = 13
2125 IF B$ = "E" THEN LET L1 = 14
2126 IF B$ = "F" THEN LET L1 = 15

2130 IF c$ >= "0" OR c$ <= "9" THEN L2 = VAL(c$)
2131 IF c$ = "A" THEN LET L2 = 10
2132 IF c$ = "B" THEN LET L2 = 11
2133 IF c$ = "C" THEN LET L2 = 12
2134 IF c$ = "D" THEN LET L2 = 13
2135 IF c$ = "E" THEN LET L2 = 14
2136 IF c$ = "F" THEN LET L2 = 15

2140 IF D$ >= "0" OR D$ <= "9" THEN L3 = VAL(D$)
2141 IF D$ = "A" THEN LET L3 = 10
2142 IF D$ = "B" THEN LET L3 = 11
2143 IF D$ = "C" THEN LET L3 = 12
2144 IF D$ = "D" THEN LET L3 = 13
2145 IF D$ = "E" THEN LET L3 = 14
2146 IF D$ = "F" THEN LET L3 = 15


2157 IF E$ >= "0" OR E$ <= "9" THEN L4 = VAL(E$)
2151 IF E$ = "A" THEN LET L4 = 10
2152 IF E$ = "B" THEN LET L4 = 11
2153 IF E$ = "C" THEN LET L4 = 12
2154 IF E$ = "D" THEN LET L4 = 13
2155 IF E$ = "E" THEN LET L4 = 14
2156 IF E$ = "F" THEN LET L4 = 15

4000 LET F$ = A$(4, L1 + 1)
4001 LET G$ = A$(5, L2 + 1)
4002 LET J$ = A$(16, L2 + 1)
4003 LET H$ = A$(2, L3 + 1)
4004 LET K$ = A$(7, L3 + 1)
4005 LET M$ = A$(10, L3 + 1)
4006 LET O$ = A$(11, L3 + 1)
4007 LET I$ = A$(3, L4 + 1)
4008 LET L$ = A$(10, L4 + 1)
4009 LET N$ = A$(7, L4 + 1)
4010 LET P$ = A$(6, L4 + 1)
4490 CLS : PRINT : PRINT : PRINT : PRINT
4500 PRINT : PRINT "  POPRAWNY WYGL¤D WSZYSTKICH WARTO—CI": PRINT
4502 PRINT "PIERWSZE 8 ZNAKàW    "; B$; c$; " "; D$; E$; " "; F$; G$; " "; H$; I$
4503 PRINT
4507 PRINT "    SAFE-1           "; B$; J$; " "; K$; L$; " "; B$; J$; " "; K$; L$: PRINT
4508 PRINT "    BEZ KODU         "; B$; J$; " "; M$; N$; " "; B$; J$; " "; M$; N$: PRINT
4509 PRINT "    KOD              "; B$; J$; " "; O$; P$; " "; B$; J$; " "; O$; P$: PRINT

9993 PRINT : PRINT : PRINT
9995 INPUT "LICZYMY DALEJ "; S$
9996 IF S$ = "N" OR S$ = "n" THEN GOTO 9999
9997 GOTO 1700

9999 END

