Ralph
Wade
wade@eglin.af.mil
8/13/98 12:33 PM
External Osc
options:email:wade@eglin.af.mil
Is there any way to connect a external Osc to the SX28 and  have the SX key program it with out removing the osc from osc1 pin?
My application is extremely small SSOP type boards. I do not have room to put a jumper for programming on the board. Not to mention that the vibration would be a problem with a jumper in my environment

