Stephen
Holland
support@scenix.com
11/25/98 3:40 PM
Re: Slow RC oscillator
options:email:support@scenix.com
Wayne Glasser on 11/25/98 1:45 AM said:

>>>>
>>The errata sheets I have say that the slow internal RC oscillator speed was to be fixed in V2.4 however we have devices dated 9818 which still run at about 3.2Mhz when measured
>>

Wayne,

We are currently preparing documentation about how to access the internal oscillator trim bits to tune the internal RC clock frequency. In the future this will be done at the factory before shipping - we apaologize for any inconvenience.

Scenix
