psychic
electron
psychtron
10/26/98 12:36 PM
1 Gbit supercomputer for < $100.00
options:email:psychtron

Does anyone have experience with multi-processor 
supercomputer achitectures for signal processing
and pattern recognition. Can stacked scenixs run in parallel
handle 32 bit alu operations if carry/borrow bits
are passed to the next level? What data flow topologies would be used for different applications? i.e. video,
stereo audio, dolby, sensor, etc. Any ideas welcome.

