juergen
leistikow
juergen.leistikow@uni-essen.de
8/26/98 3:31 AM
rtcc extern pin interrrupt
options:email:juergen.leistikow@uni-essen.de
Dear madam, dear sir,
for my next applications with the SX18/28 it is importend
for me to know, when the rtcc extern pin interrupt will be
available. I do not need an exact date, but i would like to
know, if you can make the chip do this until the end of 98 ?

With kind regards
 
              j.leistikow  

