psychic 
electron
psychtron@hotmail.com
10/26/98 1:09 PM
1 GigaFlop supercomputer for < $100.00
options:email:psychtron@hotmail.com
 I meant to say 1 GigaFlop supercomputer. I'm experimenting
with an inline data flow technique with embedded command
passing for processing sensor data from A/D's
Has anyone used the 12bit eeprom table read command
for fast lookup's of stored functions or extended 16/32bit
accumulate/divide to improve the signal to noise ratio of sampled analog signals. Would anyone be interested in an integrated A/D, D/A signal processing development board for audio and video algorithm exploration???                                                             psychic e-
