zafar
ullah
sultana_zafar@msn.com
10/8/98 3:38 PM
Re: programming sx..
options:email:sultana_zafar@msn.com
jacky szymanski on 9/30/98 5:35 AM said:

>>
>>
>>how identify the sync pulse for a correct programmation before the 16 pulses of instructions of instruction and data
>>
>> (no information in the serial programmation information)
>>
>>                         thanks 
>>

>>                                    js
>>

Hello Jacky,

There is no pulse during the sync cycle. Thanks.

regards,
Zafar
