Jim
Dove
wjtmjimd@broadcast.net
10/5/98 10:23 AM
Programmer software
options:email:wjtmjimd@broadcast.net
I need software for the Parallax SXKEY hardware that will run in Windows 3.1x.  I need to use it with my laptop which only has WFW3.11 on it, and I am not interested in win9x, and have no way to install it on the laptop anyway(no cd).  All of the systems my hardware & software are used with run only on DOS as they are dedicated automation systems, and windows serves no purpose whatsoever on those system.  I need to be able to reprogram my systems in the field.

Another option would be another programmer and software.

Anyone know of anything?
