Harvey
Gilmartin
harveyg@ix.netcom.com
1/4/99 7:30 PM
isp programming problem
options:email:harveyg@ix.netcom.com
I am trying to program an sx28ac using isp without success. I have followed the directions in User's Manual v1.0 pp151-153 for entering the ISP mode. When I switch OSC1 (pin  28) to 12.5V, OSC2 (pin 27) goes to a state of open drain, no pullup, no sync pulses (i.e. no isp mode). I have tried both internal and external osc sequences with same results.
Any suggestions? 
What is the state of FUSE,FUSEX words when device is shipped? When I apply an external oscillator to OSC1, there is no output on OSC2. 

