kai
klein
kai.klein@t-online.de
1/18/99 7:16 AM
SX Assembler and Modulus or Division
options:email:kai.klein@t-online.de
Hi Mr. Microcontroller !! 

I have view questions about youre Assembler for Scenix Chips, 
I wrote allready to Mr.e-mail kzahnert@dd.sda.de. but he cant help me with my question. 

I develop a Temp Sensor Modul with a Dallas DS1820 Temp Sensor. 

now i must calculate with some variables 
example: dont work like this!! 
mov    temp,temp//100        shell meen temp Modulus 100    ? 
mov    temp1,temp//100        shell meen temp Modulus 100    ? 
or 
mov    temp,temp/100        temp Divide by 100    ? 
mov    temp1,temp/100        temp Divide by 100    ? 

can i do this with youre Assembler ? or must i have a Rutine for this ? 
i see on the page 45 in your SX-Key Development System Manual Ver.0.7 
Binary Operators, have you view examples or is this not implemented yet. (i have the standart 
examples from Scenix) 

Hellllp !!!!

  

