Don
McKenzie
don@dontronics.com
9/27/98 5:18 PM
Scenix Simmstick?
options:email:don@dontronics.com

It has been a thought of mine to produce a Scenix Simmstick
some time in the future, however as I haven't had first hand experience with the Micro, or programming interfacing circuitry, I would appreciate any feedback as to what is required.
There is a little additional info at:
http://www.dontronics.com/scenix.html
