mike
linse
linse@ao.com
9/10/98 2:26 PM
rtcc & prescaler datasheet description
options:email:linse@ao.com
July '98 SX datasheet pg 19, Par. 10.0: "...and an 8-bit programmable prescaler extends the rtcc to 16 bits". Would it be more accurate to say that "an 8-bit programmable prescaler divides the input to the rtcc by a programmable divisor? According to Par. 10.3, the prescaler contents are not accessible to be read by a program, so you don't get '16 bits' of count resolution.



