kai
klein
kai.klein@t-online.de
10/5/98 3:44 PM
i correct the message !! Clock Problems
options:email:kai.klein@t-online.de
Kai Klein on 10/5/98 3:32 PM said:

>>Hi there,>>
>>i wrote a programm on an 28 pin SX,>>
>>i programed 2 serial ports one port with 300bps and one port with 9600bps (internal osc with 4MHZ)i tested the sicurit on the demo board from parallax, it worked fine.>>
>>>>
>>i tried the same program on my one pcb with an >>18 pin SX <<and the speed on the serial ports is not the same now and i dont now why ??>>
>>>>
is there a difference between the two chips ??

>>mayby some one has the same problem in the past, and has a solution for my>>
>>thanks !!
>>

