Stephen
Holland
support@scenix.com
9/15/98 12:12 PM
Re: C-Compiler
options:email:support@scenix.com
sanggug Park on 9/14/98 5:25 PM said:

>>Is that possible to compile SX-Series by using the >>
>>C-Compiler?>>
>>If that is possible?>>
>>Would you introduce some C-Compiler?>>
>>
>>

Sanggug,

Actually, there are several C compilers currently under development by various vendors. Bytecraft will have one available soon, and there is another which just became available from Grich RC Inc. Their website has more info at http://members.aol.com/sxcompiler - check it out...

Scenix
