Loren
Blaney
loren_blaney@idcomm.com
10/21/98 10:39 AM
Re: Programmer software
options:email:loren_blaney@idcomm.com
Stephen Holland on 10/7/98 11:24 AM said:

>>Jim Dove on 10/5/98 10:23 AM said:>>
>>>>
>>>>I need software for the Parallax SXKEY hardware that will run in Windows 3.1x.  I need to use it with my laptop which only has WFW3.11 on it, and I am not interested in win9x, and have no way to install it on the laptop anyway(no cd).  All of the systems my hardware & software are used with run only on DOS as they are dedicated automation systems, and windows serves no purpose whatsoever on those system.  I need to be able to reprogram my systems in the field.>>>>
>>>>>>>>
>>>>Another option would be another programmer and software.>>>>
>>>>>>>>
>>>>Anyone know of anything?>>
>>>>>>
>>>>
>>>>
>>Please contact Parallax about availability of Windows 3.1 versions of their SXKey software. However, there are other programming tools available soon, in a variety of platforms. Check back often for more details!>>
>>>>
>>Scenix
>>

If you have a rev C or eariler version of the SX-Key, you can use SxProg to run it under DOS. It's available from Eric's Scenix web site at:

http://www.brouhaha.com/~eric/scenix/sxprog/


