wouter
van ooijen
wf@xs4all.nl
1/14/99 11:49 AM
Re: isp programming
options:email:wf@xs4all.nl
Hello Zafar 

>>The 12.5V should be able to supply 2.5 ma of current.>>
Could I have read this somewhere in the manuals?
If so then I seem to have missed an important section!

>>To answer your second question: You can read the FUSE word before issue the ERASE command and re-program the FUSE word>>
That's an answer to another question (how do I restore the original osc setting). My qestion was: how do I enter programming mode when I don't know the osc setting. The sx manual p151 and p152 give the two methods for resp. external and internal setting, but that setting can be read only after entering programming mode!
