Seth
Hollar
shollar@bsac.eecs.berkeley.edu
9/17/98 1:52 PM
tuning fork crystal
options:email:shollar@bsac.eecs.berkeley.edu
I tried hooking up a 1 MHz tuning fork crystal to the 28SX MCU, but it doesn't seem to oscillate.  I've tried both LP and XT modes on the MCU but to no avail.  My capacitances are 15 pF and 50 pF respectively with a >1Mohm parallel resistor.  Any suggestions would be greatly appreciated.

