Stephen
Holland
support@scenix.com
10/6/98 4:44 PM
Re: Bypass Capacitor
options:email:support@scenix.com
Charles Davis on 9/30/98 6:20 AM said:

>>Does Scenix have a recommended size/type of bypass capacitor for the SX?  I have been using a 100K pf cap without any problems, but it was suggested to me that because of the high clock speed, this was too large a value.>>
>>
>>


Actually, 10uF has been a good value from our experience here...

Scenix
