Stephen
Holland
support@scenix.com
9/12/98 6:02 PM
Re: In System Programming Specs
options:email:support@scenix.com
new-scenix-user singhpk on 9/11/98 4:10 AM said:

>>>>
>>The In System programming specs for serial and >>
>>parallel programming lokk very good. >>
>>>>
>>In order to build a simple programmer(read one 8255 on a ISA card in a PC), would it be easier to use the parallel progamming specs  specs due to its relaxed timings ?>>
>>>>
>>Can someone publish some application notes with some >>
>>simple SX chip progammer circuit (PC based, parallel port with some simple like 8255 ) and  more importantly some>>
>>(pseudo or) real code(in C or pascal) to program these chips via parallel mode .>>
>>>>
>>That SX-Key hardware is just too expensive , and lots of peple would be satisfied with much simpler programmers. >>
>>The 16F84 can be programmed just with a couple of transistors and diodes off the parallel port of a PC.>>
>>>>
>>>>
>>regards>>
>>>>
>>>>
>>
>>

Mr. Singh,

You are correct, A parallel programmer would be easier to develop, because of it's relaxed timing requirements.

There are several efforts currently underway to provide 'freeware' serial and parallel programmers. You can find more information on the first one I know of at www.sxpoint.com

Scenix
