Greg
Poe
gregory_c_poe@mail.northgrum.com
10/22/98 7:36 AM
Re: Still OSC Problems 
options:email:gregory_c_poe@mail.northgrum.com
Scenix,

FYI:
I am using several SX-28's (9818) with the internal 4MHZ clock, and none of them operate within the +-8% range. They are working around 3.3MHz. 

Greg Poe

>>The internal 4MHz oscillator is only accurate to ±8%, and subsequntly is not always accurate enough for proper UART speed. It is suggested to use an external oscillator for best results.>>
>>>>
>>I tried your code and it looks fine...>>
>>>>
>>Scenix
>>

