psychic
electron
psychtron@hotmail.com
9/3/98 5:42 PM
Re: USB and Hot Wire interface firmware
options:email:psychtron@hotmail.com


>>hello,>>
>>Are there any plans to allow use of scenix processors
      with the USB high speed serial bus???

 I also require the use of USB, is anyone working on this???
 Also Hot Wire for interfacing to HDTV video signals
 
        Psychic electron     psychtron@hotmail.com
