juergen
leistikow
juergen.leistikow@uni-essen.de
8/27/98 3:14 AM
rtcc interrupt by external source
options:email:juergen.leistikow@uni-essen.de
Hello Scenix,

thanks for your quick response.
Sorry, there was a missunderstanding. So i better tell you,
what i want to do in my next application.
In that next ap. i need two 8 bit ports and 1 interrupt source. The interrupt source should be the rtcc pin in turbo
mode and not assigned to the prescaler !
The rtcc register will be preset to ffh so that the next
transition on rtcc pin will generate an interrupt.
In your errata sheet from may 26 that option is announced
not to be yet implemented.
So, when will that be enabled?

With kind regards
     
              j.leistikow
