Stephan
Pejouan
scp@wridge.com
9/18/98 11:23 AM
Re: New Newsgroup
options:email:scp@wridge.com
JUST TESTING - IGNORE

Chris Fogelklou on 8/10/98 5:41 PM said:

>>Welcome to the Scenix newsgroup.  Myself and the other support staff here at Scenix will be posting answers to common questions on this newsgroup.  We will also be checking the newsgroup regularly, so feel free to use it for any technical questions you may have about the Scenix SX line.>>
>>
>>

