Kai
Klein
kai.klein@t-online.de
10/8/98 9:50 AM
RS 232 with send signal
options:email:kai.klein@t-online.de

hi,
i have big problems to get my serial to a transmitter running,
i need a hi signal on pin (RB.6) when i send a byte or string to the serial output pin ra.2, to bring my transmitter online when i am sending data.

i use the demo program from scenix with 9600 8n1. for example.

how can i do this ?
please help.
 
