Stephen
Holland
support@scenix.com
9/3/98 7:29 PM
Re: USB and Hot Wire interface firmware
options:email:support@scenix.com
psychic electron on 9/3/98 5:42 PM said:

>>>>
>>>>
>>>>hello,>>>>
>>>>Are there any plans to allow use of scenix processors>>
>>      with the USB high speed serial bus???>>
>>>>
>> I also require the use of USB, is anyone working on this???>>
>> Also Hot Wire for interfacing to HDTV video signals>>
>> >>
>>        Psychic electron     psychtron@hotmail.com
>>

There is an effort underway to provide a USB solution for the SX.

If IEEE1394 - aka 'Fire Wire' (Hot Wire?) is what you are looking for, we haven't studied the feasability for it yet, but it seems unlikely to work at it's intended high speeds of 400Mbps. Maybe at a slower rate, or with a future rev of SX, we'll see.

Scenix
