<html>
<HEAD>
   <TITLE> Криптология, алгоритмы шифрования </TITLE>
   <META NAME="Author" CONTENT="Sergey Protasov ">
   <META NAME="KeyWords" CONTENT=" hack, crack, ИБЛЕТ, троян, хакер, взлом, вирус, _El, Протасов, Сергей, FAQ, Soft, exploit ">
   <META NAME="Description" CONTENT="">
</HEAD>
<BODY TEXT="#ff0000" LINK="#00FF00" VLINK="#FFFFFF" BACKGROUND="bg.gif">
<table width=120 align=left>
  <tr><td>  </td></tr>
  <tr>
    <td valign=top width="120">
           <table width=120 cellspacing=0 cellpadding=0 border=2 bgcolor="#949cc6">
     <tr>
       <td>
          <table width="100%" border="1" cellspacing="0" cellpadding="0">
             <tr><td></td></tr>
          </table>
          <table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#f0DEe7">
          <tr>
             <td><img src="empty.gif" width=3 height=8 border=0 alt="">
             </td>
             <td>
             <table width=120 border="0" cellspacing="0" cellpadding="0" align="LEFT" valign="TOP">
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="security_.html"><font color="#ff4000">Security Page</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="news_.html"><font color="#ff4000">Security News</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="security_unix_.html"><font color="#ff4000">Безопасность в Unix</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="security_nt_.html"><font color="#ff4000">Безопасность в Windows</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="security_faqs_.html"><font color="#ff4000">Сборник FAQ'ов</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="phreaking_.html"><font color="#ff4000">Телефония, фрикинг</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="carding_.html"><font color="#ff4000">Кредитные карты</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="crypto_.html"><font color="#ff4000">Криптография</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="security_history_.html"><font color="#ff4000">Истории о хакерах</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="download_.html"><font color="#ff4000">Программы, утилиты</font></A></FONT>
                 </TD>
               </tr>
               <tr>
                 <td valign="TOP"><font color="#ff4000">&#0149;</font>
                 </td>
                 <TD ALIGN=left VALIGN=top WIDTH=90%><FONT SIZE=-1>
                    <a style="color=#ff4000" href="scripts_.html"><font color="#ff4000">CGI скрипты</font></A></FONT>
                 </TD>
               </tr>
             </table>
             </td>
          </tr>
          <tr>
             <td colspan="2"><img src="empty.gif" width=1 height=3 border=0 alt=""> 
             </td>
          </tr>
          </table>
          <table width="100%" border="1" cellspacing="0" cellpadding="0">
             <tr><td>
             </td></tr>
          </table>
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
             <tr>
                <td>
                   <table width="100%" height=20 border="0" cellspacing="0" cellpadding="0">
                      <tr>
                         <td><img src="empty.gif" width=5 height=1 border=0 alt="">
                         </td>
                         <td> <font size="-1"><b><a style="color=#000080" href=http://www.svp.lgg.ru/home_.html><font color="#000080">_el@geocities.com</font></a></b></font>
                         </td>
                      </tr>
                   </table>
                </td>
             </tr>
          </table>
      </td>
  </tr>
</table>
      
      
    </td>
  </tr>
</table>
<table width=600 ALIGN=center VALIGN=middle>
   <tr>
      <td align=center valign=middle WIDTH=20>
                    <img src="empty.gif" width=10 height=10 border=0 alt="">
       </td>
       <td>
               <h1 align=center> Криптология, алгоритмы шифрования </h1>


       <CENTER><IMG SRC="line.gif" BORDER=0 HEIGHT=8 WIDTH=270 ALT=""></CENTER>
<hr><br><img src="l.gif" height="11" width="15" alt=""><a href="cryptoanalysis_.html"> Методы криптоанализа классических шифров </a><img src="new.gif" border=0 height=12 width=31 alt=""><font color="#ffff00">28/01/99</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="linksecurity_.html"> Беспроводные средства связи и безопасность </a><font color="#ffff00">18/12/98</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="why_not_safe_.html"> Почему криптосистемы ненадежны? </a><font color="#ffff00">15/12/98</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="faq_hacker_10_.html"> Что такое PGP? </a><font color="#ffff00">27/09/97</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="faq_hacker_11_.html"> Что такое RSA? </a><font color="#ffff00">27/09/97</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="faq_hacker_12_.html"> Что такое Cobra? </a><font color="#ffff00">27/09/97</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="faq_hacker_14_.html"> Что такое HASP? </a><font color="#ffff00">27/09/97</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="faq_hacker_15_.html"> Что такое DES? </a><font color="#ffff00">27/09/97</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="faq_hacker_16_.html"> Что такое GOST? </a><font color="#ffff00">27/09/97</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="faq_hacker_27_.html"> Методы кpиптоанализа. </a><font color="#ffff00">27/09/97</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="faq_hacker_3_.html"> Как получить доступ к информации (r/w) на диске защищенным ADM? </a><font color="#ffff00">27/09/97</font><br>
<img src="l.gif" height="11" width="15" alt=""><a href="faq_hacker_9_.html"> О случайных числах </a><font color="#ffff00">27/09/97</font><br>
          <br><br><hr>
       <TABLE>          <TR><td><a href="http://www.lgg.ru/~svp/cgi-bin2/main.txt"><img src="http://www.lgg.ru/~svp/cgi-bin2/logger.cgi?crypto_.html" WIDTH=10 HEIGHT=10 ALT="" BORDER=0 ></a> </td>
          </TR>
       </TABLE>
    </td>
  </tr>
</table>
</body></html>