[InstallSHIELD Silent]
Version=v3.00.00
File=Response File
[DlgOrder]
Dlg0=SdBitmap-0
Dlg1=Welcome-0
Dlg2=SdRegisterUser-0
Dlg3=AskDestPath-0
Dlg4=SdSetupType-0
Dlg5=SdStartCopy-0
Dlg6=SdFinish-0
Count=7
[SdBitmap-0]
Result=1
[Welcome-0]
Result=1
[SdRegisterUser-0]
Result=1
szName=Name
szCompany=Company
[AskDestPath-0]
szPath=<ProgramFilesDir>\InstallShield\InstallShield Express BC++ 5.02 Edition
Result=1
[SdSetupType-0]
Result=301
szDir=<ProgramFilesDir>\InstallShield\InstallShield Express BC++ 5.02 Edition
[SdStartCopy-0]
Result=1
[SdFinish-0]
Result=1
bOpt1=0
bOpt2=0
